# Generated by Django 4.0.5 on 2022-06-22 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('birthdate', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.PositiveIntegerField()),
            ],
        ),
    ]
